project:
  name: pxlngn.net
  type: static
  build:
    command: npm run build
    output: dist
  environment:
    NODE_VERSION: 20
  deployment:
    bootstrap:
      excludes:
        - .git
        - .github
        - node_modules
        - .deploy-now
    recurring:
      excludes:
        - .git
        - .github
        - node_modules
        - .deploy-now
